- hosts: apache
  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted
      become: yes

  tasks:
    - name: 'Copiando o alive.htm'
      template:
        src: 'templates/alive.htm.j2'
        dest: '/usr/share/httpd/noindex/alive.htm'
      become: yes

    - name: 'Configura o httpd.conf'
      template:
        src: 'templates/httpd.conf.j2'
        dest: '/etc/httpd/conf/httpd.conf'
        backup: yes
      become: yes
      notify:
        - restart apache
